site_name: CoppeliaSim 4.10 con Python
site_description: Manual de Robótica y Simulación para Formación Profesional
site_author: José Aguilera

theme:
  name: material
  language: es
  # custom_dir: overrides
  logo: assets/logos/logo.svg
  favicon: assets/logos/favicon.png
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - content.code.copy
    - content.code.annotate

  font:
    text: Roboto
    code: JetBrains Mono

  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo

extra_css:
  - assets/css/coppeliasim-fp.css

extra_javascript:
  - assets/js/coppeliasim-fp.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 2-4
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - mermaid2
  - fp_book
  - minify:
      minify_html: true

nav:
  - Inicio: index.md
  - Prólogo: prologo.md
  - Introducción: introduccion.md

  - Parte I. Fundamentos:
      - Presentación: parte1/index.md
      - "Capítulo 1. ¿Por qué aprender robótica mediante simulación?": parte1/capitulo01.md
      - "Capítulo 2. Instalación y configuración inicial": parte1/capitulo02.md
      - "Capítulo 3. Conociendo la interfaz de CoppeliaSim": parte1/capitulo03.md
      - "Capítulo 4. Creando nuestra primera simulación": parte1/capitulo04.md
      - "Capítulo 5. Manipulación de objetos y sistemas de coordenadas": parte1/capitulo05.md
      - "Capítulo 6. Primera conexión entre Python y CoppeliaSim": parte1/capitulo06.md
  
  - Parte II. Robótica móvil:
      - Presentación: parte2/index.md
      - "Capítulo 7. Primer contacto con el Pioneer P3DX": parte2/capitulo07.md
      - "Capítulo 8. Sensores en robots móviles": parte2/capitulo08.md
      - "Capítulo 9. Control del movimiento del Pioneer P3DX": parte2/capitulo09.md
      - "Capítulo 10. Navegación autónoma mediante sensores": parte2/capitulo10.md
      - "Capítulo 11. Programación estructurada del Pioneer P3DX": parte2/capitulo11.md


  - Parte III:
    - Introducción: parte3/index.md

  - Parte IV:
      - Introducción: parte4/index.md

  - Parte V:
      - Introducción: parte5/index.md

  - Parte VI:
      - Introducción: parte6/index.md
      
  - Editorial:
      - Manual de estilo: editorial/manual_estilo.md

