site_name: CoppeliaSim 4.10 con Python
site_description: Manual de Robótica y Simulación para Formación Profesional
site_author: José Aguilera

theme:
  name: material
  language: es
  custom_dir: overrides
  logo: assets/logos/logo.svg
  favicon: assets/logos/favicon.png

  font:
    text: Roboto
    code: JetBrains Mono

  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate

extra_css:
  - assets/css/coppeliasim-fp.css

extra_javascript:
  - assets/js/coppeliasim-fp.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - mermaid2
  - minify:
      minify_html: true

nav:
  - Inicio: index.md
  - Parte I:
      - Primer contacto: parte1/index.md
      - Capítulo 1: parte1/capitulo01.md
      - Capítulo 2: parte1/capitulo02.md
      - Capítulo 3: parte1/capitulo03.md
  - Parte II:
      - Primer robot: parte2/index.md
  - Parte III:
      - Python y CoppeliaSim: parte3/index.md
  - Parte IV:
      - Curso práctico: parte4/index.md
  - Parte V:
      - Solucionario: parte5/index.md
  - Parte VI:
      - Recursos profesor: parte6/index.md


plugins:
  - search
  - mermaid2
  - fp_book
  - minify:
      minify_html: true