name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v5

      - name: Instalar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Comprobar sitio
        run: mkdocs build --strict

      - name: Publicar en GitHub Pages
        run: mkdocs gh-deploy --force